# Generated by Django 3.0b1 on 2020-07-21 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SysImageSetting',
            fields=[
                ('edition', models.IntegerField(blank=True, null=True)),
                ('path', models.CharField(max_length=126, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'sys_image_setting',
                'managed': False,
            },
        ),
    ]
