# Generated by Django 3.0b1 on 2021-01-05 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_sysimagesetting'),
    ]

    operations = [
        migrations.CreateModel(
            name='SysGrant',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('menu_id', models.CharField(blank=True, max_length=32, null=True)),
                ('menu_name', models.CharField(blank=True, max_length=32, null=True)),
                ('menu_grant', models.CharField(blank=True, max_length=32, null=True)),
            ],
            options={
                'db_table': 'sys_grant',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SysUserGrant',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('user_id', models.CharField(blank=True, max_length=32, null=True)),
                ('user_account', models.CharField(blank=True, max_length=32, null=True)),
                ('user_name', models.CharField(blank=True, max_length=32, null=True)),
                ('grant_id', models.CharField(blank=True, max_length=32, null=True)),
                ('user_grant', models.CharField(blank=True, max_length=32, null=True)),
            ],
            options={
                'db_table': 'sys_user_grant',
                'managed': False,
            },
        ),
    ]
